#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Использование: $0 \"текст\""
    exit 1
fi

text="$*"

len=${#text}

line="+"
for ((i = 0; i < len + 2; i++)); do
    line+="-"
done
line+="+"

echo "$line"
echo "| $text |"
echo "$line"
